name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]['name']")
          echo Using default scheme: $default
          echo $default > default

      - name: Build
        run: |
          scheme=$(cat default)
          echo "Using scheme: $scheme"

          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then 
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$`"
          else 
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          fi
          
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          echo "Building with file: $file_to_build"

          # Build and analyze
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty
          exit_code=${PIPESTATUS[0]}
          
          # Check if build was successful
          if [ $exit_code -ne 0 ]; then
            echo "Build failed with exit code $exit_code"
            exit $exit_code
          fi
